// Categories object defining the hierarchical structure of academic fields and their subcategories
export const ProjectCategories = {
    Physics: [
      "Classical Mechanics",
      "Electromagnetism",
      "Thermodynamics",
      "Quantum Mechanics",
      "Relativity",
      "Nuclear Physics",
      "Particle Physics",
      "Condensed Matter Physics",
      "Astrophysics",
      "Optics",
      "Plasma Physics",
      "Biophysics",
    ],
    Chemistry: [
      "Organic Chemistry",
      "Inorganic Chemistry",
      "Physical Chemistry",
      "Analytical Chemistry",
      "Biochemistry",
    ],
    Biology: [
      "Botany",
      "Zoology",
      "Microbiology",
      "Genetics",
      "Molecular Biology",
      "Cell Biology",
      "Anatomy",
      "Physiology",
      "Ecology",
      "Evolutionary Biology",
      "Biotechnology",
      "Bioinformatics",
      "Immunology",
      "Neuroscience",
      "Agricultural Biology",
      "Marine Biology",
      "Environmental Biology",
    ],
    "Earth Sciences": [
      "Geology",
      "Geophysics",
      "Meteorology",
      "Oceanography",
      "Natural hazards and risk assessment",
      "Hydrology",
    ],
    "Space Science": [
      "Astronomy",
      "Astrophysics",
      "Planetary science",
      "Space exploration",
      "Astrobiology",
      "Space weather",
      "Gravitational physics and relativity",
      "Space policy and law",
    ],
    Technology: [
      "Information Technology (IT)",
      "Communication Technology",
      "Biotechnology",
      "Energy & Environmental Technology",
      "Space Technology",
      "Medical Technology",
      "Nanotechnology",
      "Agricultural Technology",
      "Transportation Technology",
    ],
    Engineering: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Civil Engineering",
      "Computer Science & Engineering (CSE)",
      "Electronics & Communication Engineering (ECE)",
      "Chemical Engineering",
      "Aerospace Engineering",
      "Biomedical Engineering",
      "Environmental Engineering",
      "Industrial & Production Engineering",
      "Materials Science & Engineering",
      "Marine & Ocean Engineering",
      "Nuclear Engineering",
      "Agricultural Engineering",
      "Petroleum & Mining Engineering",
      "Data Science Engineering",
    ],
    "Pure Mathematics": [
      "Algebra",
      "Calculus",
      "Geometry",
      "Number Theory",
      "Analysis",
      "Topology",
      "Graph theory",
    ],
    "Applied Mathematics": [
      "Probability and Statistics",
      "Linear Algebra",
      "Optimization and Operations Research",
      "Mathematical Biology & Epidemiology",
      "Financial Mathematics & Actuarial Science",
      "Computational Mathematics",
      "Mathematical Physics",
      "Mathematical Modelling & Simulation",
      "Cryptography & Information Security",
      "Data Science & Machine Learning",
      "Geophysical & Environmental Mathematics",
      "Economics and Computation",
      "Game Theory",
    ],
  };
  